### ISSUE TITLE
A way to push message to a channel outside of the handler?

### ISSUE THREAD

**Issue by Gonzih** [jwilm/chatbot#30]
Hi, Im looking at this library as a possible solution to implement my own bot, but I don't see how one can post messages outside of the handler. For example I have a thread thot polls status from some remote service and on failure posts message to the chat. Is there already api in this library that exposes this fuctionality?

Thanks!

**Comment by jwilm** [comment]
It's not currently supported, but I don't think it would be too bad to add. The outgoing message loop in all the adapters just receives on a channel. I think that adding a method to the `Adapter` trait like `get_sender` would be a decent approach. Would probably want to return an associated type of `Adapter` like `Sender : SendMessage`.

**Comment by Gonzih** [comment]
Yeah, that sounds like a perfect solution for my use case.
