### ISSUE TITLE
openssl package conflict

### ISSUE THREAD

**Issue by jackkav** [jwilm/chatbot#31]
error: native library `openssl` is being linked to by more than one version of the same pac
kage, but it can only be linked once; try updating or pinning your dependencies to ensure t
hat this package only shows up once

  openssl-sys v0.6.7
  openssl-sys v0.9.10

**Comment by jwilm** [comment]
Can you provide any more info? This library doesn't depend directly upon openssl.

**Comment by jackkav** [comment]
`cargo new hello_world --bin`
then edit Cargo.toml
```
[package]
name = "hello_world"
version = "0.1.0"

[dependencies]
chatbot = "0.2.3"
```
`cargo build`
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: native library `openssl` is being linked to by more than one version of the same pac
kage, but it can only be linked once; try updating or pinning your dependencies to ensure t
hat this package only shows up once

  openssl-sys v0.6.7
  openssl-sys v0.9.10
